### ISSUE TITLE
Errors during jooq:codegen

### ISSUE THREAD

**Issue by emssik** [sean8223/jooq-sbt-plugin#13]
Hello,

when I try execute jooq:codegen I have some errors:

[info] Initialising properties  : /jooq-config5871881329987835950.xml
[error] Unmarshal warning        : cvc-complex-type.2.4.b: The content of element 'generator' is not complete. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd":name, "http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd":strategy, "http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd":database, "http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd":generate}' is expected.
[error] Unmarshal warning        : cvc-complex-type.2.4.b: The content of element 'configuration' is not complete. One of '{"http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd":jdbc}' is expected.
[error] The <jdbc/> tag is mandatory. For details, see http://www.jooq.org/xsd/jooq-codegen-3.3.0.xsd
[info] Initialising properties  : /jooq-config8327691138014868648.xml

and after

error] org.jooq.util.GeneratorException: Error generating code for schema public
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268)
[error] 	at org.jooq.util.GenerationTool.run(GenerationTool.java:426)
[error] 	at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
[error] 	at org.jooq.util.GenerationTool.main(GenerationTool.java:151)
[error] Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 9
[error] (?s:^.*?\Rpackage\s+(.*?);?\R.*?$)
[error]          ^
[error] 	at java.util.regex.Pattern.error(Pattern.java:1924)
[error] 	at java.util.regex.Pattern.escape(Pattern.java:2416)
[error] 	at java.util.regex.Pattern.atom(Pattern.java:2164)
[error] 	at java.util.regex.Pattern.sequence(Pattern.java:2046)
[error] 	at java.util.regex.Pattern.expr(Pattern.java:1964)
[error] 	at java.util.regex.Pattern.group0(Pattern.java:2847)
[error] 	at java.util.regex.Pattern.sequence(Pattern.java:2018)
[error] 	at java.util.regex.Pattern.expr(Pattern.java:1964)
[error] 	at java.util.regex.Pattern.compile(Pattern.java:1665)
[error] 	at java.util.regex.Pattern.<init>(Pattern.java:1337)
[error] 	at java.util.regex.Pattern.compile(Pattern.java:1022)
[error] 	at org.jooq.util.JavaWriter.beforeClose(JavaWriter.java:121)
[error] 	at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:237)
[error] 	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3131)
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:265)
[error] 	... 3 more
[error] Cannot read /jooq-config8327691138014868648.xml. Error : Error generating code for schema public
[error] org.jooq.util.GeneratorException: Error generating code for schema public
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268)
[error] 	at org.jooq.util.GenerationTool.run(GenerationTool.java:426)
[error] 	at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
[error] 	at org.jooq.util.GenerationTool.main(GenerationTool.java:151)
[error] Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 9
[error] (?s:^.*?\Rpackage\s+(.*?);?\R.*?$)
[error]          ^
[error] 	at java.util.regex.Pattern.error(Pattern.java:1924)
[error] 	at java.util.regex.Pattern.escape(Pattern.java:2416)
[error] 	at java.util.regex.Pattern.atom(Pattern.java:2164)
[error] 	at java.util.regex.Pattern.sequence(Pattern.java:2046)
[error] 	at java.util.regex.Pattern.expr(Pattern.java:1964)
[error] 	at java.util.regex.Pattern.group0(Pattern.java:2847)
[error] 	at java.util.regex.Pattern.sequence(Pattern.java:2018)
[error] 	at java.util.regex.Pattern.expr(Pattern.java:1964)
[error] 	at java.util.regex.Pattern.compile(Pattern.java:1665)
[error] 	at java.util.regex.Pattern.<init>(Pattern.java:1337)
[error] 	at java.util.regex.Pattern.compile(Pattern.java:1022)
[error] 	at org.jooq.util.JavaWriter.beforeClose(JavaWriter.java:121)
[error] 	at org.jooq.util.GeneratorWriter.close(GeneratorWriter.java:237)
[error] 	at org.jooq.util.JavaGenerator.generateSchema(JavaGenerator.java:3131)
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
[error] 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:265)
[error] 	... 3 more
[error] Usage : GenerationTool <configuration-file>

My build.sbt:

(...)
seq(jooqSettings:_*)

fork in Test := true

(...)

libraryDependencies ++= Seq(
(...)
  "org.postgresql" % "postgresql" % "9.4-1201-jdbc41" % "jooq"
)

jooqVersion := "3.6.3"

jooqOptions := Seq("jdbc.driver" -> "org.postgresql.Driver",
  "jdbc.url" -> "jdbc:postgresql://localhost:5432/db_as_template",
  "jdbc.user" -> "user",
  "jdbc.password" -> "password",
  "generator.database.name" -> "org.jooq.util.postgres.PostgresDatabase",
  "generator.database.inputSchema" -> "public",
  "generator.target.packageName" -> "sowase.jooq")

Regards

Daniel Roziecki

**Comment by emssik** [comment]
That was my mistake. 

I have multiproject, and had seq(jooqSettings:_*) in wrong build.sbt.

Regards

**Comment by lukaseder** [comment]
We're having an important regression in jOOQ 3.6.3 when using JDK < 1.8: https://github.com/jOOQ/jOOQ/issues/4576. This will be fixed on our side as soon as possible.

Probably, this issue here is related.
